# Create table for ISO Country codes
#
# see: http://www.iso.org/iso/country_codes/iso_3166_code_lists/english_country_names_and_code_elements.htm


class CreateCountries < ActiveRecord::Migration
  def self.up
    create_table :countries, :force => true do |t|
      t.string :name
      t.string :code, :limit => 2
      t.timestamps
    end
    
    Country.create :name => 'AFGHANISTAN', :code => 'AF'
    Country.create :name => 'ÅLAND ISLANDS', :code => 'AX'
    Country.create :name => 'ALBANIA', :code => 'AL'
    Country.create :name => 'ALGERIA', :code => 'DZ'
    Country.create :name => 'AMERICAN SAMOA', :code => 'AS'
    Country.create :name => 'ANDORRA', :code => 'AD'
    Country.create :name => 'ANGOLA', :code => 'AO'
    Country.create :name => 'ANGUILLA', :code => 'AI'
    Country.create :name => 'ANTARCTICA', :code => 'AQ'
    Country.create :name => 'ANTIGUA AND BARBUDA', :code => 'AG'
    Country.create :name => 'ARGENTINA', :code => 'AR'
    Country.create :name => 'ARMENIA', :code => 'AM'
    Country.create :name => 'ARUBA', :code => 'AW'
    Country.create :name => 'AUSTRALIA', :code => 'AU'
    Country.create :name => 'AUSTRIA', :code => 'AT'
    Country.create :name => 'AZERBAIJAN', :code => 'AZ'
    Country.create :name => 'BAHAMAS', :code => 'BS'
    Country.create :name => 'BAHRAIN', :code => 'BH'
    Country.create :name => 'BANGLADESH', :code => 'BD'
    Country.create :name => 'BARBADOS', :code => 'BB'
    Country.create :name => 'BELARUS', :code => 'BY'
    Country.create :name => 'BELGIUM', :code => 'BE'
    Country.create :name => 'BELIZE', :code => 'BZ'
    Country.create :name => 'BENIN', :code => 'BJ'
    Country.create :name => 'BERMUDA', :code => 'BM'
    Country.create :name => 'BHUTAN', :code => 'BT'
    Country.create :name => 'BOLIVIA', :code => 'BO'
    Country.create :name => 'BOSNIA AND HERZEGOVINA', :code => 'BA'
    Country.create :name => 'BOTSWANA', :code => 'BW'
    Country.create :name => 'BOUVET ISLAND', :code => 'BV'
    Country.create :name => 'BRAZIL', :code => 'BR'
    Country.create :name => 'BRITISH INDIAN OCEAN TERRITORY', :code => 'IO'
    Country.create :name => 'BRUNEI DARUSSALAM', :code => 'BN'
    Country.create :name => 'BULGARIA', :code => 'BG'
    Country.create :name => 'BURKINA FASO', :code => 'BF'
    Country.create :name => 'BURUNDI', :code => 'BI'
    Country.create :name => 'CAMBODIA', :code => 'KH'
    Country.create :name => 'CAMEROON', :code => 'CM'
    Country.create :name => 'CANADA', :code => 'CA'
    Country.create :name => 'CAPE VERDE', :code => 'CV'
    Country.create :name => 'CAYMAN ISLANDS', :code => 'KY'
    Country.create :name => 'CENTRAL AFRICAN REPUBLIC', :code => 'CF'
    Country.create :name => 'CHAD', :code => 'TD'
    Country.create :name => 'CHILE', :code => 'CL'
    Country.create :name => 'CHINA', :code => 'CN'
    Country.create :name => 'CHRISTMAS ISLAND', :code => 'CX'
    Country.create :name => 'COCOS (KEELING) ISLANDS', :code => 'CC'
    Country.create :name => 'COLOMBIA', :code => 'CO'
    Country.create :name => 'COMOROS', :code => 'KM'
    Country.create :name => 'CONGO', :code => 'CG'
    Country.create :name => 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', :code => 'CD'
    Country.create :name => 'COOK ISLANDS', :code => 'CK'
    Country.create :name => 'COSTA RICA', :code => 'CR'
    Country.create :name => "CÔTE D\'IVOIRE", :code => 'CI'
    Country.create :name => 'CROATIA', :code => 'HR'
    Country.create :name => 'CUBA', :code => 'CU'
    Country.create :name => 'CYPRUS', :code => 'CY'
    Country.create :name => 'CZECH REPUBLIC', :code => 'CZ'
    Country.create :name => 'DENMARK', :code => 'DK'
    Country.create :name => 'DJIBOUTI', :code => 'DJ'
    Country.create :name => 'DOMINICA', :code => 'DM'
    Country.create :name => 'DOMINICAN REPUBLIC', :code => 'DO'
    Country.create :name => 'ECUADOR', :code => 'EC'
    Country.create :name => 'EGYPT', :code => 'EG'
    Country.create :name => 'EL SALVADOR', :code => 'SV'
    Country.create :name => 'EQUATORIAL GUINEA', :code => 'GQ'
    Country.create :name => 'ERITREA', :code => 'ER'
    Country.create :name => 'ESTONIA', :code => 'EE'
    Country.create :name => 'ETHIOPIA', :code => 'ET'
    Country.create :name => 'FALKLAND ISLANDS (MALVINAS)', :code => 'FK'
    Country.create :name => 'FAROE ISLANDS', :code => 'FO'
    Country.create :name => 'FIJI', :code => 'FJ'
    Country.create :name => 'FINLAND', :code => 'FI'
    Country.create :name => 'FRANCE', :code => 'FR'
    Country.create :name => 'FRENCH GUIANA', :code => 'GF'
    Country.create :name => 'FRENCH POLYNESIA', :code => 'PF'
    Country.create :name => 'FRENCH SOUTHERN TERRITORIES', :code => 'TF'
    Country.create :name => 'GABON', :code => 'GA'
    Country.create :name => 'GAMBIA', :code => 'GM'
    Country.create :name => 'GEORGIA', :code => 'GE'
    Country.create :name => 'GERMANY', :code => 'DE'
    Country.create :name => 'GHANA', :code => 'GH'
    Country.create :name => 'GIBRALTAR', :code => 'GI'
    Country.create :name => 'GREECE', :code => 'GR'
    Country.create :name => 'GREENLAND', :code => 'GL'
    Country.create :name => 'GRENADA', :code => 'GD'
    Country.create :name => 'GUADELOUPE', :code => 'GP'
    Country.create :name => 'GUAM', :code => 'GU'
    Country.create :name => 'GUATEMALA', :code => 'GT'
    Country.create :name => 'GUERNSEY', :code => 'GG'
    Country.create :name => 'GUINEA', :code => 'GN'
    Country.create :name => 'GUINEA-BISSAU', :code => 'GW'
    Country.create :name => 'GUYANA', :code => 'GY'
    Country.create :name => 'HAITI', :code => 'HT'
    Country.create :name => 'HEARD ISLAND AND MCDONALD ISLANDS', :code => 'HM'
    # Country.create :name => 'HOLY SEE (VATICAN CITY STATE)', :code => 'VA'
    Country.create :name => 'HONDURAS', :code => 'HN'
    Country.create :name => 'HONG KONG', :code => 'HK'
    Country.create :name => 'HUNGARY', :code => 'HU'
    Country.create :name => 'ICELAND', :code => 'IS'
    Country.create :name => 'INDIA', :code => 'IN'
    Country.create :name => 'INDONESIA', :code => 'ID'
    Country.create :name => 'IRAN, ISLAMIC REPUBLIC OF', :code => 'IR'
    Country.create :name => 'IRAQ', :code => 'IQ'
    Country.create :name => 'IRELAND', :code => 'IE'
    Country.create :name => 'ISLE OF MAN', :code => 'IM'
    Country.create :name => 'ISRAEL', :code => 'IL'
    Country.create :name => 'ITALY', :code => 'IT'
    Country.create :name => 'JAMAICA', :code => 'JM'
    Country.create :name => 'JAPAN', :code => 'JP'
    Country.create :name => 'JERSEY', :code => 'JE'
    Country.create :name => 'JORDAN', :code => 'JO'
    Country.create :name => 'KAZAKHSTAN', :code => 'KZ'
    Country.create :name => 'KENYA', :code => 'KE'
    Country.create :name => 'KIRIBATI', :code => 'KI'
    Country.create :name => "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF", :code => 'KP'
    Country.create :name => 'KOREA, REPUBLIC OF', :code => 'KR'
    Country.create :name => 'KUWAIT', :code => 'KW'
    Country.create :name => 'KYRGYZSTAN', :code => 'KG'
    Country.create :name => "LAO PEOPLE'S DEMOCRATIC REPUBLIC", :code => 'LA'
    Country.create :name => 'LATVIA', :code => 'LV'
    Country.create :name => 'LEBANON', :code => 'LB'
    Country.create :name => 'LESOTHO', :code => 'LS'
    Country.create :name => 'LIBERIA', :code => 'LR'
    Country.create :name => 'LIBYAN ARAB JAMAHIRIYA', :code => 'LY'
    Country.create :name => 'LIECHTENSTEIN', :code => 'LI'
    Country.create :name => 'LITHUANIA', :code => 'LT'
    Country.create :name => 'LUXEMBOURG', :code => 'LU'
    Country.create :name => 'MACAO', :code => 'MO'
    Country.create :name => 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', :code => 'MK'
    Country.create :name => 'MADAGASCAR', :code => 'MG'
    Country.create :name => 'MALAWI', :code => 'MW'
    Country.create :name => 'MALAYSIA', :code => 'MY'
    Country.create :name => 'MALDIVES', :code => 'MV'
    Country.create :name => 'MALI', :code => 'ML'
    Country.create :name => 'MALTA', :code => 'MT'
    Country.create :name => 'MARSHALL ISLANDS', :code => 'MH'
    Country.create :name => 'MARTINIQUE', :code => 'MQ'
    Country.create :name => 'MAURITANIA', :code => 'MR'
    Country.create :name => 'MAURITIUS', :code => 'MU'
    Country.create :name => 'MAYOTTE', :code => 'YT'
    Country.create :name => 'MEXICO', :code => 'MX'
    Country.create :name => 'MICRONESIA, FEDERATED STATES OF', :code => 'FM'
    Country.create :name => 'MOLDOVA, REPUBLIC OF', :code => 'MD'
    Country.create :name => 'MONACO', :code => 'MC'
    Country.create :name => 'MONGOLIA', :code => 'MN'
    Country.create :name => 'MONTENEGRO', :code => 'ME'
    Country.create :name => 'MONTSERRAT', :code => 'MS'
    Country.create :name => 'MOROCCO', :code => 'MA'
    Country.create :name => 'MOZAMBIQUE', :code => 'MZ'
    Country.create :name => 'MYANMAR', :code => 'MM'
    Country.create :name => 'NAMIBIA', :code => 'NA'
    Country.create :name => 'NAURU', :code => 'NR'
    Country.create :name => 'NEPAL', :code => 'NP'
    Country.create :name => 'NETHERLANDS', :code => 'NL'
    Country.create :name => 'NETHERLANDS ANTILLES', :code => 'AN'
    Country.create :name => 'NEW CALEDONIA', :code => 'NC'
    Country.create :name => 'NEW ZEALAND', :code => 'NZ'
    Country.create :name => 'NICARAGUA', :code => 'NI'
    Country.create :name => 'NIGER', :code => 'NE'
    Country.create :name => 'NIGERIA', :code => 'NG'
    Country.create :name => 'NIUE', :code => 'NU'
    Country.create :name => 'NORFOLK ISLAND', :code => 'NF'
    Country.create :name => 'NORTHERN MARIANA ISLANDS', :code => 'MP'
    Country.create :name => 'NORWAY', :code => 'NO'
    Country.create :name => 'OMAN', :code => 'OM'
    Country.create :name => 'PAKISTAN', :code => 'PK'
    Country.create :name => 'PALAU', :code => 'PW'
    Country.create :name => 'PALESTINIAN TERRITORY, OCCUPIED', :code => 'PS'
    Country.create :name => 'PANAMA', :code => 'PA'
    Country.create :name => 'PAPUA NEW GUINEA', :code => 'PG'
    Country.create :name => 'PARAGUAY', :code => 'PY'
    Country.create :name => 'PERU', :code => 'PE'
    Country.create :name => 'PHILIPPINES', :code => 'PH'
    Country.create :name => 'PITCAIRN', :code => 'PN'
    Country.create :name => 'POLAND', :code => 'PL'
    Country.create :name => 'PORTUGAL', :code => 'PT'
    Country.create :name => 'PUERTO RICO', :code => 'PR'
    Country.create :name => 'QATAR', :code => 'QA'
    Country.create :name => 'RÉUNION', :code => 'RE'
    Country.create :name => 'ROMANIA', :code => 'RO'
    Country.create :name => 'RUSSIAN FEDERATION', :code => 'RU'
    Country.create :name => 'RWANDA', :code => 'RW'
    Country.create :name => 'SAINT BARTHÉLEMY', :code => 'BL'
    Country.create :name => 'SAINT HELENA', :code => 'SH'
    Country.create :name => 'SAINT KITTS AND NEVIS', :code => 'KN'
    Country.create :name => 'SAINT LUCIA', :code => 'LC'
    Country.create :name => 'SAINT MARTIN', :code => 'MF'
    Country.create :name => 'SAINT PIERRE AND MIQUELON', :code => 'PM'
    Country.create :name => 'SAINT VINCENT AND THE GRENADINES', :code => 'VC'
    Country.create :name => 'SAMOA', :code => 'WS'
    Country.create :name => 'SAN MARINO', :code => 'SM'
    Country.create :name => 'SAO TOME AND PRINCIPE', :code => 'ST'
    Country.create :name => 'SAUDI ARABIA', :code => 'SA'
    Country.create :name => 'SENEGAL', :code => 'SN'
    Country.create :name => 'SERBIA', :code => 'RS'
    Country.create :name => 'SEYCHELLES', :code => 'SC'
    Country.create :name => 'SIERRA LEONE', :code => 'SL'
    Country.create :name => 'SINGAPORE', :code => 'SG'
    Country.create :name => 'SLOVAKIA', :code => 'SK'
    Country.create :name => 'SLOVENIA', :code => 'SI'
    Country.create :name => 'SOLOMON ISLANDS', :code => 'SB'
    Country.create :name => 'SOMALIA', :code => 'SO'
    Country.create :name => 'SOUTH AFRICA', :code => 'ZA'
    Country.create :name => 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', :code => 'GS'
    Country.create :name => 'SPAIN', :code => 'ES'
    Country.create :name => 'SRI LANKA', :code => 'LK'
    Country.create :name => 'SUDAN', :code => 'SD'
    Country.create :name => 'SURINAME', :code => 'SR'
    Country.create :name => 'SVALBARD AND JAN MAYEN', :code => 'SJ'
    Country.create :name => 'SWAZILAND', :code => 'SZ'
    Country.create :name => 'SWEDEN', :code => 'SE'
    Country.create :name => 'SWITZERLAND', :code => 'CH'
    Country.create :name => 'SYRIAN ARAB REPUBLIC', :code => 'SY'
    Country.create :name => 'TAIWAN, PROVINCE OF CHINA', :code => 'TW'
    Country.create :name => 'TAJIKISTAN', :code => 'TJ'
    Country.create :name => 'TANZANIA, UNITED REPUBLIC OF', :code => 'TZ'
    Country.create :name => 'THAILAND', :code => 'TH'
    Country.create :name => 'TIMOR-LESTE', :code => 'TL'
    Country.create :name => 'TOGO', :code => 'TG'
    Country.create :name => 'TOKELAU', :code => 'TK'
    Country.create :name => 'TONGA', :code => 'TO'
    Country.create :name => 'TRINIDAD AND TOBAGO', :code => 'TT'
    Country.create :name => 'TUNISIA', :code => 'TN'
    Country.create :name => 'TURKEY', :code => 'TR'
    Country.create :name => 'TURKMENISTAN', :code => 'TM'
    Country.create :name => 'TURKS AND CAICOS ISLANDS', :code => 'TC'
    Country.create :name => 'TUVALU', :code => 'TV'
    Country.create :name => 'UGANDA', :code => 'UG'
    Country.create :name => 'UKRAINE', :code => 'UA'
    Country.create :name => 'UNITED ARAB EMIRATES', :code => 'AE'
    Country.create :name => 'UNITED KINGDOM', :code => 'GB'
    Country.create :name => 'UNITED STATES', :code => 'US'
    Country.create :name => 'UNITED STATES MINOR OUTLYING ISLANDS', :code => 'UM'
    Country.create :name => 'URUGUAY', :code => 'UY'
    Country.create :name => 'UZBEKISTAN', :code => 'UZ'
    Country.create :name => 'VANUATU', :code => 'VU'
    Country.create :name => 'VATICAN CITY STATE', :code => 'VA'
    Country.create :name => 'VENEZUELA', :code => 'VE'
    Country.create :name => 'VIET NAM', :code => 'VN'
    Country.create :name => 'VIRGIN ISLANDS, BRITISH', :code => 'VG'
    Country.create :name => 'VIRGIN ISLANDS, U.S.', :code => 'VI'
    Country.create :name => 'WALLIS AND FUTUNA', :code => 'WF'
    Country.create :name => 'WESTERN SAHARA', :code => 'EH'
    Country.create :name => 'YEMEN', :code => 'YE'
    Country.create :name => 'ZAMBIA', :code => 'ZM'
    Country.create :name => 'ZIMBABWE', :code => 'ZW'
  end

  def self.down
    drop_table :countries
  end
end
